apiVersion: v1
kind: Service
metadata:
  name: cue-api
  namespace: cue-system
  labels:
    app: cue-api
spec:
  selector:
    app: cue-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cue-nginx
  namespace: cue-system
  labels:
    app: cue-nginx
spec:
  selector:
    app: cue-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cue-system
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP