import MultiGraph from 'graphology';
import { HDNodeWallet, verifyMessage, SignatureLike, sha256, id, BytesLike, SigningKey } from 'ethers';
import { EventEmitter } from 'node:events';
import { forceSimulation } from "d3-force-3d";
import * as d3 from "d3-force-3d";
import { Worker, BroadcastChannel } from 'worker_threads';
import * as net from 'node:net';
import { Server } from 'socket.io';
// import { ENVIRONMENT_BLOCK } from '../../../unity2d/types/environment/environment'
import { createServer } from 'node:http';
import http from "node:http";
import url from "node:url";
// import { blue, bright, reset, WorkerBot } from '../../../unity2d';
// import { BGblue, BGgreen, BGmagenta, BGyellow, yellow } from '../../../unity2d/bin/console/console.colors';
import { Attributes } from 'graphology-types';
import { unlinkSync } from 'node:fs';
// import Blockchain from '../blockchain';
// import Memory from '../../../unity2d/types/storage/memory';
// import { iBlock } from '../blockchain/interfaces';
// import { BLOCK_MATRIX, BLOCK_VECTOR } from '../blockchain/types';
// import { iMemory, iUseMemory } from '../memory/interfaces';
// import { HISTORY } from '../memory/types';
import { join } from 'node:path';
// import { Broker } from '../broker/index';
// import { INPUT, SINK, OUTPUT, STREAM, SOURCE } from '../network/types';
// import { ENTITY, PATH, ID, CONTENT, IDENTITY } from '../../types/types';
// import { Graph } from '../graph';
// import { iContent, iDefinitions, iDescription, iIdentity, iParameters } from '../../types/interfaces';
import MerkleTree from 'merkletreejs';
// import { DOCUMENT } from '../../../unity2d/types/marketplace/document';
import Redis from 'ioredis';
import Graph from 'graphology';
import { bright, BGblue, reset, blue, yellow, WorkerBot } from '../unity2d';
import { BGyellow } from '../unity2d/bin/console/console.colors';
import { encryptData } from '../unity2d/bin/crypto/pgp';
import { encodeJSON } from '../unity2d/bin/encoders/encode.json';
import { ASSET } from '../unity2d/types/marketplace/asset';
import { DOCUMENT } from '../unity2d/types/marketplace/document';
import { SERVICE } from '../unity2d/types/marketplace/service';
import { NODE } from '../unity2d/types/network/node';
import Memory from '../unity2d/types/storage/memory';
import { iBlock } from './modules/blockchain/interfaces';
import { Broker } from './modules/broker';
import { INPUT, SINK, OUTPUT, STREAM, SOURCE } from './modules/network/types';
import { iContent, iDefinitions, iDescription, iParameters } from './types/interfaces';
import { ID, PATH, CONTENT, IDENTITY, FEATURE, WEIGHT } from './types/types';
import { isProperties } from './modules/graph/assertions';
import { BLOCK, HISTORY } from './src/server/test/modules/environment';
// import { BLOCK, HISTORY } from './test/modules/scene';
// import { encryptData } from '../../../unity2d/bin/crypto/pgp';
// import { encodeJSON } from '../../../unity2d/bin/encoders/encode.json';
// import { ASSET } from '../../../unity2d/types/marketplace/asset';
// import { SERVICE } from '../../../unity2d/types/marketplace/service';
// import { NODE } from '../../../unity2d/types/network/node';